before_script:
  - apt-get update && apt-get install -y -qq rsync openssh-client zip unzip
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - echo "$SSHKEY" | tr -d '\r' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan $DEPLOY_DOMAIN >> ~/.ssh/known_hosts

deploy-staging:
  stage: deploy
  only: staging
  environment: staging
  script:
    - rsync -ravz --delete --exclude .git --exclude .env  --exclude vendor ./ $DEPLOY_USER@$DEPLOY_DOMAIN:/$SOURCE_PATH
    - ssh $DEPLOY_USER@$DEPLOY_DOMAIN "bash -c 'cd $SOURCE_PATH && rm -f composer.lock && composer install && php artisan migrate'"

deploy-production:
  stage: deploy
  only: production
  environment: production
  script:
    - rsync -ravz --delete --exclude .git --exclude .env  --exclude vendor ./ $DEPLOY_USER@$DEPLOY_DOMAIN:/$SOURCE_PATH
    - ssh $DEPLOY_USER@$DEPLOY_DOMAIN "bash -c 'cd $SOURCE_PATH && rm -f composer.lock && composer install && php artisan migrate'"

deploy-develop:
  stage: deploy
  only: build/dev
  environment: develop
  script:
    - rsync -ravz --delete --exclude .git --exclude .env  --exclude vendor ./ $DEPLOY_USER@$DEPLOY_DOMAIN:/$SOURCE_PATH
