include:
  - project: $CICD_REPO
    ref: main
    file: '/becom/.gitlab-ci.yml'
    rules:
      - if: '$CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "build/dev"'
test:
  stage: deploy
  script: exit 0
  only:
    - notfound