<?php

return [
    'campaign' => [
        'create' => 'create_campaign',
        'edit' => 'edit_campaign',
        'delete' => 'delete_campaign',
        'show' => 'show_campaign',
        'index' => 'index_campaign',
    ],
    'contact' => [
        'create' => 'create_contact',
        'edit' => 'edit_contact',
        'delete' => 'delete_contact',
        'show' => 'show_contact',
        'index' => 'index_contact',
    ],
    'contact_list' => [
        'create' => 'create_contact_list',
        'edit' => 'edit_contact_list',
        'delete' => 'delete_contact_list',
        'show' => 'show_contact_list',
        'index' => 'index_contact_list',
    ],
    'remind' => [
        'create' => 'create_remind',
        'edit' => 'edit_remind',
        'delete' => 'delete_remind',
        'show' => 'show_remind',
        'index' => 'index_remind',
    ],
    'note' => [
        'create' => 'create_note',
        'edit' => 'edit_note',
        'delete' => 'delete_note',
        'show' => 'show_note',
        'index' => 'index_note',
    ],
    'position' => [
        'create' => 'create_position',
        'edit' => 'edit_position',
        'delete' => 'delete_position',
        'show' => 'show_position',
        'index' => 'index_position',
    ],
    'company' => [
        'create' => 'create_company',
        'edit' => 'edit_company',
        'delete' => 'delete_company',
        'show' => 'show_company',
        'index' => 'index_company',
    ],
    'status' => [
        'create' => 'create_status',
        'edit' => 'edit_status',
        'delete' => 'delete_status',
        'show' => 'show_status',
        'index' => 'index_status',
    ],
    'form' => [
        'create' => 'create_form',
        'edit' => 'edit_form',
        'delete' => 'delete_form',
        'show' => 'show_form',
        'index' => 'index_form',
    ],
    'section_template' => [
        'create' => 'create_section_template',
        'edit' => 'edit_section_template',
        'delete' => 'delete_section_template',
        'show' => 'show_section_template',
        'index' => 'index_section_template',
    ],
    'website_page' => [
        'create' => 'create_website_page',
        'edit' => 'edit_website_page',
        'delete' => 'delete_website_page',
        'show' => 'show_website_page',
        'index' => 'index_website_page',
    ],
    'email' => [
        'create' => 'create_email',
        'edit' => 'edit_email',
        'delete' => 'delete_email',
        'show' => 'show_email',
        'index' => 'index_email',
    ],
    'mail_template' => [
        'create' => 'create_mail_template',
        'edit' => 'edit_mail_template',
        'delete' => 'delete_mail_template',
        'show' => 'show_mail_template',
        'index' => 'index_mail_template',
    ],
    'smtp_account' => [
        'create' => 'create_smtp_account',
        'edit' => 'edit_smtp_account',
        'delete' => 'delete_smtp_account',
        'show' => 'show_smtp_account',
        'index' => 'index_smtp_account',
    ],
    'website' => [
        'create' => 'create_website',
        'edit' => 'edit_website',
        'delete' => 'delete_website',
        'show' => 'show_website',
        'index' => 'index_website',
    ],
    'footer' => [
        'create' => 'create_footer',
        'edit' => 'edit_footer',
        'delete' => 'delete_footer',
        'show' => 'show_footer',
        'index' => 'index_footer',
    ],
];
